<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <li class="nav_li"><a href="index.php?url=account" class="nav_a">Compte</a></li>
        <li class="nav_li"><a href="index.php?url=contact" class="nav_a">Contact</a></li>
        <li class="nav_li"><a href="index.php?url=home" class="nav_a">Accueil</a></li>
        <li class="nav_li"><a href="index.php?url=subscription" class="nav_a">Inscription</a></li>
    </nav>
    <main>
        <?= $content ?>
    </main>
</body>
</html>