<!-- Aside should be visible only when the user is identified -->
<div class="aside">
    <!-- <h3>Aside</h3> -->
    <img class ="mascotte" src="../app/pictures/hector-sevilla-l-cute-snakys-trasnparent.png" alt="">
    <div>
        <div class="asideDiv">
            <!-- This part of aside is for different form to add contenu -->
            <h3 class= "titleAside">Aidez Citrangue</h3>
            <!-- <a href="index.php?url=formAddSubject">Ajouter un thème</a> -->
        
            <ul>
                <li><a href="index.php?url=formAddQuestion">Ajouter question</a></li>
                <li><a href="index.php?url=nop">Faire un don</a></li>
                <li><a href="index.php?url=nop">Participer</a></li>
                <br>
            </ul>
        </div>
        
        <div class="asideDiv">    
            <h3 class= "titleAside">Communauté</h3>

            <ul>
            <li><a href="index.php?url=nop">Top 10 users</a></li>
                <li><a href="index.php?url=nop">Discussions</a></li>
                <li><a href="index.php?url=nop">Leagues</a></li>
                <li><a href="index.php?url=nop">Amis</a></li>
                <br>
            </ul>
            
            <!-- <a href="index.php?url=formNewNotion">Ajouter une notion</a>
            <a href="index.php?url=classExplanation">Explications</a> -->
        </div>
    </div>
    
</div>