<!-- Aside should be visible only when the user is identified -->
<div class="aside">
    <h3>Aside</h3>
    <img src="../app/pictures/hector-sevilla-l-cute-snakys-trasnparent.png" alt="">
    <div>
        <!-- This part of aside is for different form to add contenu -->
        <h3 class= "titleAside">Aidez Citrangue</h3>
        <a href="index.php?url=formAddSubject">Ajouter un thème</a>
        <a href="index.php?url=formNewQuestion">Ajouter une question</a>
        <a href="index.php?url=formNewNotion">Ajouter une notion</a>
        <a href="index.php?url=classExplanation">Explications</a>
    </div>
    
</div>