<body class="bodyClass">
    

    <h2>Cours</h2>

    <?php
    // Aside must be visible here. Nav also.
    require_once "../app/controllers/navController.php";
    require_once "../app/controllers/asideController.php";
    ?>
    <div class="classOld">
        <h3>Anciens cours</h3>
    </div>
    <div class="classCurrent" id="classCurrent">
        <h3>Cours actuels</h3>
        
        <div class="categoryClassCurrent">
            <?php foreach($existingUnits as &$existingUnit): ?>
                <div class = "containerClass">
                    <div class="cercle">
                        <a href="index.php?url=exercice&amp;name=<?=$existingUnit['unit_name'];?>"  class = "linkClass">
                            <img class="pictureClass", src="../app/pictures/classPictures/book.png" alt="">
                        </a>
                    </div>
                    <p class= "textClass"> <?=$existingUnit['unit_name'] ; ?> </p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="classFuture">
        <h3>Futurs cours</h3>
    </div>

</body>