<h2>Connexion</h2>
<div id="container">
                <!-- zone de connexion -->
                
    <form action="verification.php" method="POST">
        <h1>Connexion</h1>
                    
        <label><b>Adresse mail</b></label>
        <input type="text" placeholder="Entrez votre mail" name="usermail" required>

        <label><b>Mot de passe</b></label>
        <input type="password" placeholder="Entrer le mot de passe" name="password" required>

        <input type="submit" id='submit' value='LOGIN' >
    </form>
</div>