<h2>Exercice</h2>


<body>

    <!-- start Quiz button -->
    <div class="start_btn"><button>Commencer</button></div>
    <!-- Info Box -->
    <div class="info_box">
        <div class="info-title"><span>Quelques règles</span></div>
        <div class="info-list">
            <div class="info">1. Vous n'aurez que <span>15 seconds</span> pour chaque question.</div>
            <div class="info">2. Une fois que vous avez choisi une réponse, elle n'est pas modifiable.</div>
            <div class="info">3. Vous ne pouvez plus répondre lorsque le temps est écoulé.</div>
            <div class="info">4. Vous ne pouvez pas quitter temps que le quiz est en route.</div>
            <div class="info">5. Le nombre de points obtenus dépend des réponses correctes.</div>
        </div>
        <div class="buttons">
            <button class="quit">Quitter</button>
            <button class="restart">Continuer</button>
        </div>
    </div>
    <!-- Quiz Box -->

    <div class="quiz_box">
        <header>
            <div class="title">Citrangue quiz</div>
            <div class="timer">
                <div class="time_left_txt">Temps restant</div>
                <div class="timer_sec">30</div>
            </div>
            <div class="time_line"></div>
        </header>
        <section>
            <div class="que_text">
                <!-- Here I've inserted question from JavaScript -->
            </div>
            <div class="option_list">
                <!-- Here I've inserted options from JavaScript -->
            </div>
        </section>
        <!-- footer of Quiz Box -->
        <footer>
            <div class="total_que">
                <!-- Here I've inserted Question Count Number from JavaScript -->
            </div>
            <button class="next_btn">Suivant</button>
        </footer>
    </div>
    <!-- Result Box -->
    <div class="result_box">
        <div class="icon">
            <i class="fas fa-crown"></i>
        </div>
        <div class="complete_text">Bravo, vous avez terminé !</div>
        <div class="score_text">
            <!-- Here I've inserted Score Result from JavaScript -->
        </div>
        <div class="buttons">
            <button class="restart">Refaire le quiz</button>
            <button class="quit">Quitter</button>
        </div>
    </div>
    <script>
        console.log("sup");
        var js_data = <?php echo json_encode($php_data); ?>;
        // console.log(js_data)
    </script>


    <!-- Inside this JavaScript file I've inserted Questions and Options only -->
    <!-- <script src="js/questionList.js"></script> -->
    <!-- Inside this JavaScript file I've coded all Quiz Codes -->
    <script src="js/qcmScript.js"></script>
</body>
