<h2>Ajout de question</h2>
<form action="" method="post">
    <div>
        <h3>Unité</h3>
        <?php if($errorNewUnitName != NULL):?>
            <p class=errorMsg><?=$errorNewUnitName?></p>
        <?php endif;?>
        <label><b>Nom d'une nouvelle unité</b></label>
        <input type="text" placeholder="" id="newUnitName" name="newUnitName" required>

        <?php if($errorNewUnitName != NULL):?>
            <p class=errorMsg><?=$errorCurrentUnitName?></p>
        <?php endif;?>
        <label><b>Nom d'une unité actuelle</b></label>
        <select placeholder="" id="newUnitName" name="newUnitName">
            <?php
                echo $listOfExistingUnit;
            ?>
        </select>
        
    </div>

    <div>
        <h3>Notions</h3>
    </div>

    <div>
        <h3>Unité</h3>
    </div>

</form>

