
<h2>Ajout de question</h2>
    
    <!-- Form for Unit -->
    <form action="" method="post" id="unitForm">

            <h3>Unité</h3>

        <?php if($errorGeneralUnitName !== NULL):?>
            <p class=errorMsg><?=$errorGeneralUnitName?></p>
        <?php endif;?>

        <!-- New unit -->

        <?php if($errorNewUnitName !== NULL):?>
            <p class=errorMsg><?=$errorNewUnitName?></p>
        <?php endif;?>

        <label><b>Nom d'une nouvelle unité</b></label>
        <input type="text" placeholder="" id="newUnitName" name="newUnitName">


        <?php if($errorExistingUnitName === NULL):?>
            <p class=errorMsg><?=$errorExistingUnitName?></p>
        <?php endif;?>


        <label><b>Nom d'une unité actuelle</b></label>
        <select placeholder="" id="existingUnitName" name="existingUnitName">
        <option value = NULL></option>
        <?php
            foreach($listOfExistingUnit as $oneUnit){
                echo($oneUnit);
            };
        ?>
        </select>

        <label><b>Niveau de l'unité</b></label>
        <input type="range" id="unitLvl" name="unitLvl" min="0" max="5">

        <input type="submit" id='registUnit' name='registUnit' class="registerbtn" value="Ajouter" >
       
    </form>



<script type="text/javascript" src="formQuestion.js"></script>
    



