<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/app.css">
    <title>Document</title>
</head>
<header>
    <!-- TODO : Faire la nav -->
</header>

<body>
<h1>Layout</h1>
<?php echo $content ?>
    <!-- TODO : afficher aside si connecté -->
</body>

<footer>
    <!-- TODO : Faire le footer -->
</footer>
</html>