
    <div class="nav"> 
        <img class="navPictures avatar" src="../app/pictures/navPictures/avatar.png" alt="">
        <img class="navPictures book" src="../app/pictures/navPictures/book.png" alt="">
        <img class="navPictures" src="../app/pictures/navPictures/crown.png" alt="">
        <img class="navPictures logo"  src="../app/pictures/navPictures/logo1.png" alt="logo">
        <img class="navPictures book2" src="../app/pictures/navPictures/livre-de-sortileges.png" alt="">
        <img class="navPictures" src="../app/pictures/navPictures/money-bag.png" alt="">
        <img class="navPictures" src="../app/pictures/navPictures/user.png" alt="">
    </div>