
    <div class="nav"> 
        <a href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures avatar" src="../app/pictures/navPictures/avatar.png" alt="perso"></a>
        <a class="booklink" href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures book" src="../app/pictures/navPictures/book.png" alt="savoir"></a>
        <a href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures" src="../app/pictures/navPictures/crown.png" alt="succes"></a>
        <a href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures logo"  src="../app/pictures/navPictures/logo1.png" alt="logo">
        <a href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures book2" src="../app/pictures/navPictures/livre-de-sortileges.png" alt="connaissances"></a>
        <a href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures" src="../app/pictures/navPictures/money-bag.png" alt="boutique"></a>
        <a href="https://c.tenor.com/yCC38OsGnSsAAAAC/sportsmanias-technical-difficulties.gif"><img class="navPictures" src="../app/pictures/navPictures/user.png" alt="profil"></a>
    </div>