<!DOCTYPE phtml>
<html lang="fr">

    <body>
        <form  method="POST">
            <div class="container">    
                
                <h1>Inscription</h1>
                
                <?php if($errorGeneral != NULL):?>
                    <p class=errorMsg><?=$errorGeneral?></p>
                <?php endif;?>
                <label><b>Adresse mail</b></label>
                <input type="text" placeholder="Entrez votre mail" id="usermail" name="usermail" required>

                <?php if($errorPseudo != NULL):?>
                    <p class=errorMsg><?=$errorPseudo?></p>
                <?php endif;?>
                <label><b>Pseudo</b></label>
                <input type="text" placeholder="Entrez votre pseudo" id="userpseudo" name="userpseudo" required>

                <?php if($errorPwd != NULL):?>
                    <p class=errorMsg><?=$errorPwd?></p>
                <?php endif;?>
                <label><b>Mot-de-passe</b></label>
                <input type="password" placeholder="Entrer le mot de passe" id="userpwd" name="userpwd" required>

                <?php if($errorPwdCheck != NULL):?>
                    <p class=errorMsg><?=$errorPwdCheck?></p>
                <?php endif;?>
                <label><b>Répéter votre mot-de-passe</b></label>
                <input type="password" placeholder="Entrer le mot de passe" id="userpwdcheck" name="userpwdcheck" required>

                <label for="agreement">
                <input type="checkbox" name="agreement" id="agreement" value="yes"/> Je suis d'accord avec
                <a href="#" title="term of services">les règles d'utilisation</a>
                </label>

                <input type="submit" id='registerbtn' name='registerbtn' class="registerbtn" value="S'incrire" >

                <footer>Déjà Membre ? <a href="index.php?url=connexion">Connectez-vous ici</a></footer>
            </div>
        </form>
    </body>
</html>