<!DOCTYPE phtml>
<html lang="fr">

    <body>
        <form  method="POST">
            <div class="container">    
                <h1>Inscription</h1>
                        
                <label><b>Adresse mail</b></label>
                <input type="text" placeholder="Entrez votre mail" id="usermail" name="usermail" required>

                <label><b>Pseudo</b></label>
                <input type="text" placeholder="Entrez votre pseudo" id="userpseudo" name="userpseudo" required>

                <label><b>Mot-de-passe</b></label>
                <input type="password" placeholder="Entrer le mot de passe" id="userpwd" name="userpwd" required>

                <label><b>Répéter votre mot-de-passe</b></label>
                <input type="password" placeholder="Entrer le mot de passe" id="userpwdcheck" name="userpwdcheck" required>

                <label for="agreement">
                <input type="checkbox" name="agreement" id="agreement" value="yes"/> Je suis d'accord avec
                <a href="#" title="term of services">les règles d'utilisation</a>
                </label>

                <input type="submit" id='registerbtn' name='registerbtn' class="registerbtn" value="S'incrire" >

                <footer>Already a member? <a href="index.php?url=connexion">Login here</a></footer>
            </div>
        </form>
    </body>
</html>